es:
  hosts: 'http://127.0.0.1:9200'
  username: 'elastic'
  password: 'Pwd_250309'
  index_p_doc_item: 'v5_p_doc_item'
  index_p_doc_table: 'v5_p_doc_table'
  index_p_doc_fragment: 'v5_p_doc_fragment'
  index_p_file: 'v5_p_file'
  index_company: 'v5_company'
  index_doc_item: 'v5_doc_item'
  index_doc_table: 'v5_doc_table'
  index_doc_fragment: 'v5_doc_fragment'
  index_file: 'v5_file'

redis:
  host: "127.0.0.1"
  port: 6379
  db: 7
  username: ''
  password: 'Pwd_250309'

threadpool:
  doc_process_worker: 3
  doc_process_queue_size: 60
  global_worker: 80 # embedding_concurrency

proxy:
  url: http://127.0.0.1:8000

vector:
  # 选择向量数据库 zilliz / tencent / es
  model: es

zilliz:
  uri: https://xxx.tc-ap-shanghai.vectordb.zilliz.com.cn:443
  token: xxxx
  collection: test_rag_1024
  p_collection: test_rag_1024_p
  batch_size: 300
  concurrency: 12

tencent:
  uri: http://tvdb.xxxx
  username: root
  key: xxx
  database: db-test
  collection: t_rag_1024
  p_collection: t_p_rag_1024
  batch_size: 100
  concurrency: 30

textin:

parse:
  doc_parse_url: 'http://127.0.0.1:8080/api/v1/pdf_to_markdown'
  catalog_url: 'xxxx'
  parse_concurrency: '10'
  engine: 'megaparse' # doc_parser / pdf2md / megaparse

retrieve:
  fixed_table_keyword_threshold: 0.65
  retrieval_top_n: 15 # 最多召回的片段数
  retrieval_max_length: 30000 # 召回最长长度

location:
  base_file_path: '{BASE_DIR}/data/'
  summary_cache_path: '{BASE_DIR}/__summary_cache__/'
  base_doc_parse_path: '{BASE_DIR}/parse/doc-paser/parser-%s.json'
  base_catalog_path: '{BASE_DIR}/parse/catalog/catalog-backend-%s.json'
  base_frontend_catalog_path: '{BASE_DIR}/parse/catalog/catalog-%s.json'

storage:
  upload_address: 'http://127.0.0.1:8000/upload/'
  download_address: 'http://127.0.0.1:8000/download/'

infer:
  rough_rank_score: 0.9 # 检索粗排的top-p
  re_rank_score: 0.9 # 答案洗排的top-p
  question_keyword_url: 'http://127.0.0.1:30006/query_analysis'
  openkie_url: 'xxxxx'

backend:
  node_url: 'http://127.0.0.1:3000'
  parse_status: 'http://127.0.0.1:3000/api/v1/document/callback'

jaeger:
  collector_url: 'xxxxx'
  service_name: 'chatdoc'
  agent_host_name: 'localhost'
  exporter: 'none' # jaeger | console | none

llm:
  # 选择模型: gpt|tyqw|tyqwapi|chatglm|tianji|baichuan|kimichat|deepseek
  model: tyqwapi

gpt:
  proxy: 'xxxxxx'
  model: 'gpt-35-turbo-16k'

tyqw:
  url: 'xxxxx'
  model: 'qwen2-57b-a14b-instruct'

tyqwapi:
  url: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation'
  model: qwen-plus
  api_key: sk-250af6dd22034c55ad233b9a15d713a8

deepseek:
  url: 'https://api.deepseek.com/chat/completions'
  model: 'deepseek-chat'
  api_key: sk-xxxxx

tianji:
  url: 'http://chat7b.xxxx/generate'

baichuan:
  url: 'https://api.baichuan-ai.com/v1/chat/completions'
  model: 'Baichuan3-Turbo-128k'
  api_key: 'sk-xxxxx'

kimichat:
  url: 'https://api.moonshot.cn/v1/chat/completions'
  model: 'moonshot-v1-32k'
  api_key: 'sk-xxxxx'

chatglm:
  url: 'https://open.bigmodel.cn/api/paas/v4/chat/completions'
  model: 'glm-4'
  api_key: 'xxxx'

compliance:
  text_url: 'http://xxxxxx/data_censor/v1/text_censor'
  timeout: 60
  censors: shumei
  warning_text: '抱歉，您的提问内容与本知识库无关，请重新提问，谢谢！'

pdf2md:
